### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by Tendx** [burakoner/OKEx.Net#23]
it throws an excepption during my testing. I run it on windows  .net 5.

```
using (OkexClient client = new OkexClient())
{
    client.SetApiCredentials(account.AKey, account.SKey, account.Pass);
    var tickers = client.Spot_GetAllTickers(); // throw an exception
}
```

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Threading.Tasks.Task`1<CryptoExchange.Net.Objects.WebCallResult`1<!!0>> CryptoExchange.Net.RestClient.SendRequest(System.Uri, System.Net.Http.HttpMethod, System.Threading.CancellationToken, System.Collections.Generic.Dictionary`2<System.String,System.Object>, Boolean, Boolean, System.Nullable`1<CryptoExchange.Net.Objects.PostParameters>, System.Nullable`1<CryptoExchange.Net.Objects.ArrayParametersSerialization>, Int32)'.
  Source=Okex.Net
  StackTrace:
   at Okex.Net.OkexClient.<Spot_GetAllTickers_Async>d__267.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Okex.Net.OkexClient.Spot_GetAllTickers_Async(CancellationToken ct)
   at Okex.Net.OkexClient.Spot_GetAllTickers(CancellationToken ct)
   at Assets.OApi.SyncAccount(Account account, Dictionary`2 prices) in C:\Dex\Assets\OApi.cs:line 25
   at Assets.Program.Main(String[] args) in C:\Dex\Assets\Program.cs:line 34

**Comment by Tendx** [comment]
And CryptoExchange.Net is 3.9.0.

**Comment by Tendx** [comment]
I downgraded Binance.Net and Huobi.Net in the same project. Now CryptoExchange.Net is 3.8.0, and it worked.

**Comment by EgorovOleg** [comment]
> I downgraded Binance.Net and Huobi.Net in the same project. Now CryptoExchange.Net is 3.8.0, and it worked. So it seems Okex.net isn't compatible with CryptoExchange.Net 3.9.0.

Hello. I faced this problem too. I just upgraded all libraries to the highest version and updated CryptoExchange.Net to version 3.9.0. Only one version of CryptoExchange.Net gets into the assembly
