### ISSUE TITLE
pong json read error

### ISSUE THREAD

**Issue by libu1129** [burakoner/OKEx.Net#41]
okex.net version 5.1.2
newtonsoft.json version 13.0.1
error occured when recieve websocket message
------------------------------------------------------------------------

2021-11-30 11:13:34:989 | Error | OKEx WS Api | Deserialize JsonReaderException: Unexpected character encountered while parsing value: p. Path '', line 0, position 0., Path: , LineNumber: 0, LinePosition: 0. Data: pong
2021-11-30 11:13:35:005 | Warning | OKEx WS Api | Socket 4 Message not handled: pong
2021-11-30 11:13:35:006 | Error | OKEx WS Api | Deserialize JsonReaderException: Unexpected character encountered while parsing value: p. Path '', line 0, position 0., Path: , LineNumber: 0, LinePosition: 0. Data: pong
예외 발생: 'System.InvalidOperationException'(Newtonsoft.Json.dll)
2021-11-30 11:13:35:051 | Error | OKEx WS Api | Socket 5 unhandled exception during message processing: InvalidOperationException - Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Okex.Net.OkexSocketClient.OkexHandleSubscriptionResponse(SocketConnection s, SocketSubscription subscription, Object request, JToken message, CallResult`1& callResult)
   at CryptoExchange.Net.SocketClient.<>c__DisplayClass62_0.<SubscribeAndWaitAsync>b__0(JToken data)
   at CryptoExchange.Net.Sockets.PendingRequest.CheckData(JToken data)
   at CryptoExchange.Net.Sockets.SocketConnection.ProcessMessage(String data)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.Handle[T](List`1 handlers, T data)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.HandleMessage(Byte[] data, Int32 offset, Int32 count, WebSocketMessageType messageType)

**Comment by 8perezm** [comment]
I get the same error.
